name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Build with Gradle
        run: ./gradlew build

      - name: Get version
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ steps.get_version.outputs.VERSION }}
          body: |
            ## Changes in this Release
            
            ### Added
            - TLV Library v${{ steps.get_version.outputs.VERSION }}
            
            ### Fixed
            - Bug fixes and improvements
            
            ## Installation
            
            ### Gradle (Kotlin DSL)
            ```kotlin
            dependencies {
                implementation(files("tlv-library-${{ steps.get_version.outputs.VERSION }}.jar"))
            }
            ```
            
            ### Maven
            Download the JAR and add to your project classpath.
            
            ## Files
            - `tlv-library-${{ steps.get_version.outputs.VERSION }}.jar` - Main library
            - `tlv-library-${{ steps.get_version.outputs.VERSION }}-sources.jar` - Source code
            - `tlv-library-${{ steps.get_version.outputs.VERSION }}-javadoc.jar` - Documentation
          draft: false
          prerelease: false

      - name: Upload Main JAR
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./build/libs/tlv-library-${{ steps.get_version.outputs.VERSION }}.jar
          asset_name: tlv-library-${{ steps.get_version.outputs.VERSION }}.jar
          asset_content_type: application/java-archive

      - name: Upload Sources JAR
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./build/libs/tlv-library-${{ steps.get_version.outputs.VERSION }}-sources.jar
          asset_name: tlv-library-${{ steps.get_version.outputs.VERSION }}-sources.jar
          asset_content_type: application/java-archive

      - name: Upload Javadoc JAR
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./build/libs/tlv-library-${{ steps.get_version.outputs.VERSION }}-javadoc.jar
          asset_name: tlv-library-${{ steps.get_version.outputs.VERSION }}-javadoc.jar
          asset_content_type: application/java-archive